/*
 * This file is generated by jOOQ.
 */
package hello.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmNotInStock implements Serializable {

    private static final long serialVersionUID = 663860100;

    private Integer pFilmCount;

    public FilmNotInStock() {}

    public FilmNotInStock(FilmNotInStock value) {
        this.pFilmCount = value.pFilmCount;
    }

    public FilmNotInStock(
        Integer pFilmCount
    ) {
        this.pFilmCount = pFilmCount;
    }

    public Integer getPFilmCount() {
        return this.pFilmCount;
    }

    public void setPFilmCount(Integer pFilmCount) {
        this.pFilmCount = pFilmCount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FilmNotInStock (");

        sb.append(pFilmCount);

        sb.append(")");
        return sb.toString();
    }
}
