/*
 * This file is generated by jOOQ.
 */
package hello.tables.daos;


import hello.tables.Country;
import hello.tables.records.CountryRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CountryDao extends DAOImpl<CountryRecord, hello.tables.pojos.Country, Integer> {

    /**
     * Create a new CountryDao without any configuration
     */
    public CountryDao() {
        super(Country.COUNTRY, hello.tables.pojos.Country.class);
    }

    /**
     * Create a new CountryDao with an attached configuration
     */
    public CountryDao(Configuration configuration) {
        super(Country.COUNTRY, hello.tables.pojos.Country.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(hello.tables.pojos.Country object) {
        return object.getCountryId();
    }

    /**
     * Fetch records that have <code>country_id IN (values)</code>
     */
    public List<hello.tables.pojos.Country> fetchByCountryId(Integer... values) {
        return fetch(Country.COUNTRY.COUNTRY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>country_id = value</code>
     */
    public hello.tables.pojos.Country fetchOneByCountryId(Integer value) {
        return fetchOne(Country.COUNTRY.COUNTRY_ID, value);
    }

    /**
     * Fetch records that have <code>country IN (values)</code>
     */
    public List<hello.tables.pojos.Country> fetchByCountry(String... values) {
        return fetch(Country.COUNTRY.COUNTRY_, values);
    }

    /**
     * Fetch records that have <code>last_update IN (values)</code>
     */
    public List<hello.tables.pojos.Country> fetchByLastUpdate(Timestamp... values) {
        return fetch(Country.COUNTRY.LAST_UPDATE, values);
    }
}
